# 14장

## 자바에서의 예외
- 우리가 예상한, 혹은 예상치 못한 일이 발생하는 것을 미리 예견하고 안전장치를 하는 것

## try와 catch
- try 블록으로 감싸진 곳에서 예외가 발생하면 catch 블록으로 넘어간다.
- catch 블록이 끝나면 다음 코드가 진행된다. (Exception일 경우만, Error라면 멈춘다.)
```java
try{
    // if 예외 발생        
}catch(Exception e){
    // 실행
}
```
## 블록
- try에서 선언한 변수는 catch에서 사용할수 없다.
- 자바에서 변수는 블록 단위로 구분된다.
```java
public class Basic {
    public static void main(String[] args)  {
        Basic sample = new Basic();
        sample.throwMyException(13);
    }
    private void throwMyException(int number) {
        
        if (number > 12){
            try {
                int a = 0;
                System.out.println(a+1);
                throw new MyException("number is over than 12");
            } catch (MyException e) {
                System.out.println(a+2); // 컴파일 에러
            }
        }
    }
}
```

## finally
- try, catch 다음에 finally는 무조건 실행된다.

## 두 개 이상의 catch
- 모든 Exception의 부모는 Exception class 이다.
- catch가 여러개일 때 부모 Exception 먼저 나오면 자식 Exception은 실행될일이 없기 때문에 컴파일 에러가 발생한다.
```java
public class Basic {
    public static void main(String[] args)  {
        Basic sample = new Basic();
        sample.throwMyException(13);
    }
    private void throwMyException(int number) {
        int[] intArray = new int[5];

        try {
            System.out.println(intArray[5]);
        }
        catch (Exception e){
            System.out.println("exception");
        }
        catch (ArrayIndexOutOfBoundsException e) { // 컴파일 에러 발생 
            System.out.println("array exception");
        }
    }
}
```

## 예외라 불리는 것들의 실체
- 모든 예외라 불리는 것들은 모두 Throwable class를 상속 받는다.
- Throwable 직속 자식은 Error, Exception Class가 있다.
- Exception의 직속 자식중 RuntimeExcpetion과 이를 상속받은 클래스는 unchecked exception 이라고 한다.
- 나머지는 checked exception 이라고 한다.
- 예외의 종류는 error, checked exception, uncheckded exception 이 있다.

## throws

